import type { NextPage } from "next";
import Head from "next/head";
import Works from "../components/works";
import Mast from "../components/mast";
import Skills from "../components/skills";
import Flyout from "../components/flyout";
import Footer from "../components/footer";
import { useState } from "react";

const Home: NextPage = () => {
  const [who, setWho] = useState('jamescape')

  const handler = (x: string) => {
    setWho(x)
  }

  return (
    <div>
      <Head>
        <title>chris mcgowen.</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Mast />
      <h2 className="p-2 backdrop-blur-sm font-bold text-2xl rounded-t-xl text-center">Check Out My Work</h2>
      <Works handling={handler} />
      <Skills />
      <Flyout prop={who} />
      <Footer />
    </div>
  );
};

export default Home;
